### ISSUE TITLE
A World of Keflings (USA eShop game) spills off edge of GamePad screen when swapped

### ISSUE THREAD

**Issue by vaguerant** [wiiu-env/SwipSwapMe#3]
Using SwipSwapMe (or the older SwapDRC) with this game results in the image not fitting on the GamePad screen, like so:

![IMG_20220310_154927_270](https://user-images.githubusercontent.com/5259025/157592634-e84f1d46-592e-450c-967c-57c52f55ca1c.jpg)

The origin (top left) is the same, but the TV resolution--looks like 720p--doesn't get resized for the GamePad screen, so it's falling off the bottom and right of the GamePad screen. Obviously, the game isn't playable in this state.

This game is exclusively available on the eShop in North America. There is also a free, limited-use demo available, so assuming you've got a North American Wii U, you shouldn't need to buy anything to test further.

Getting more legally grey, you could alternatively download the free demo from NUS via alternative means. This bypasses the demo play limit (I assume this is imposed by the eShop app itself?), but ethically I don't think "pirating" a free demo is particularly dicey. The demo itself still includes a 30 minute time limit on your play sessions, so it's not akin to downloading the full game in any way.

**Comment by Maschell** [comment]
Should be fixed with https://github.com/wiiu-env/SwipSwapMe/commit/567e286b6ece5a4886914f9cc90efd0dc5c5d130
